version: '3'

services:
  # api:
  #   build: ./
  #   ports:
  #     - 5001:80
  #   environment:
  #     - PORT=80
  #     - HOST=localhost
  #     - DUMMY_MEMBER_PHONE=${DUMMY_MEMBER_PHONE}
  #     - MONGO_URL=${MONGO_URL}
  #     - ADMIN_PASSWORD=${ADMIN_PASSWORD}
  device:
    privileged: true
    devices:
      - /dev/kvm/
    image: budtmo/docker-android-x86-11.0
    ports:
      - 6080:6080
      - 5554:5554
      - 5555:5555
    environment:
      - DEVICE=Samsung Galaxy S10